pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the forked repository
                // git 'https://github.com/pulividyavathi/Jenkins-Zero-To-Hero.git'
                git url: 'https://github.com/pulividyavathi/Jenkins-Zero-To-Hero/tree/main/java-jenkins-pipeline/java-hello-world', branch: 'main'

            }
        }

        stage('Build') {
            steps {
                // Build the project using Maven
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run tests (JUnit)
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Optionally, we can deploy or do further actions
                echo 'Deploying application...'
            }
        }
    }

    post {
        success {
            echo 'Build and Test successful'
        }
        failure {
            echo 'Build or Test failed'
        }
    }
}
