pipeline {
    agent {
        docker 'maven:3-jdk-11' // Use Maven Docker image with JDK 11
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the forked repository
                // git 'https://github.com/pulividyavathi/Jenkins-Zero-To-Hero.git'
                git credentialsId: '966b5f41-ab87-46a3-b2c1-756c0eb56c2b', 
                url: 'https://github.com/pulividyavathi/Jenkins-Zero-To-Hero.git',
                branch: 'main'
                // git url: 'https://github.com/pulividyavathi/Jenkins-Zero-To-Hero/tree/main/java-jenkins-pipeline/java-hello-world', branch: 'main'

            }
        }

        stage('Build') {
            steps {
                // Build the project using Maven
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run tests (JUnit)
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Optionally, we can deploy or do further actions
                echo 'Deploying application...'
            }
        }
    }

    post {
        success {
            echo 'Build and Test successful'
        }
        failure {
            echo 'Build or Test failed'
        }
    }
}
